<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->arrayNode('array')
                ->info('Twig "array" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('currency')
                ->info('Twig "currency" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('inline')
                ->info('Twig "inline" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('basePath')
                        ->info(
                            'Base path to restrict file inlining. ' .
                            'Also, all calls to the "inline" function will be relative to this path.',
                        )
                        ->cannotBeEmpty()
                        ->defaultValue('%kernel.project_dir%/templates')
                    ->end()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('sort')
                ->info('Twig "sort" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('time')
                ->info('Twig "time" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('locale')
                        ->info('Optional locale for date and time representation.')
                        ->defaultNull()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('type')
                ->info('Twig "type" extension configuration.')
                ->addDefaultsIfNotSet()
                ->children()
                    ->booleanNode('enabled')
                        ->defaultTrue()
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Optional prefix before function and filter names.')
                        ->defaultValue('')
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
